# Mac OS X (https://github.com/travis-ci-tester/toolchain-table)

language:
    - objective-c

install:
    - brew install cmake
    - brew install python3
    # install cmake toolchains and script
    - POLLY_VERSION="0.8.0"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_TAG="3.3.2-p0"
    - CMAKE_VERSION="3.3.2"
    - wget "https://github.com/ruslo/CMake/releases/download/v${CMAKE_TAG}/cmake-${CMAKE_VERSION}-Darwin-x86_64.tar.gz"
    - tar xf "cmake-${CMAKE_VERSION}-Darwin-x86_64.tar.gz"
    - export PATH="`pwd`/cmake-${CMAKE_VERSION}-Darwin-x86_64/bin:${PATH}"
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

env:
    - PROJECT_DIR=tests/simple TOOLCHAIN=default
    - PROJECT_DIR=tests/issue/22 TOOLCHAIN=default
    - PROJECT_DIR=tests/issue/24/unit TOOLCHAIN=default
    - PROJECT_DIR=tests/issue/107 TOOLCHAIN=default
    - PROJECT_DIR=tests/issue/109/unit TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_create_args_file TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_create_dependency_entry TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_generate_qt_info TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_get_dependency_list TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_pack_directory TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_process_dependency_node TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_register_dependency TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_setup_msvc TOOLCHAIN=default
    - PROJECT_DIR=tests/hunter_unpack_directory TOOLCHAIN=default
    - PROJECT_DIR=tests/autotools-merge-lipo TOOLCHAIN=default

script:
    - python3 ./jenkins.py
