language:
    - objective-c

install:
    - brew install cmake
    - brew install python3
    # install cmake
    - CMAKE_VERSION="3.0.2-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX="`pwd`/_install/" -DCMAKE_BUILD_TYPE=Release -DCMAKE_USE_SYSTEM_CURL=YES
    -   cmake --build _builds --target install
    -   export PATH="`pwd`/_install/bin:${PATH}"
    - cd ..
    # -- end
    # install cmake toolchains and script
    - POLLY_VERSION="0.6.0"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export POLLY_ROOT="`pwd`/polly-${POLLY_VERSION}"
    - export PATH="${POLLY_ROOT}/bin:${PATH}"
    # -- end

env:
    #
    - PROJECT_DIR=examples/Boost TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Boost TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Boost TOOLCHAIN=xcode
    - PROJECT_DIR=examples/Boost TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Boost TOOLCHAIN=analyze
    #
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=xcode
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=analyze
    #
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=xcode
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=analyze
    #
    - PROJECT_DIR=examples/GTest TOOLCHAIN=default
    - PROJECT_DIR=examples/GTest TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/GTest TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/GTest TOOLCHAIN=xcode
    - PROJECT_DIR=examples/GTest TOOLCHAIN=gcc
    - PROJECT_DIR=examples/GTest TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/GTest TOOLCHAIN=analyze
    #
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=default
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=xcode
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=gcc
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/OpenSSL TOOLCHAIN=analyze
    #
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=default
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=xcode
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Sugar TOOLCHAIN=analyze

script:
    - which cmake
    - cmake --version
    - python3 ./jenkins.py
