language:
    - objective-c

before_install:
    - brew update

install:
    - brew install python3
    - brew install cmake

env:
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_boost
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_boost_ios_library
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_boost_library
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_combined_release_debug
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_no_install
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_openssl
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_openssl_ios
    - TEST_DIR=cmake/schemes TEST_NAME=tests/url_sha1_release_debug
    - TEST_DIR=examples TEST_NAME=Sugar
    - TEST_DIR=examples TEST_NAME=GTest
    - TEST_DIR=examples TEST_NAME=Boost
    - TEST_DIR=examples TEST_NAME=Boost-filesystem
    - TEST_DIR=examples TEST_NAME=Boost-stdlibcxx
    - TEST_DIR=examples TEST_NAME=Boost-ios

script:
    - cd ${TEST_DIR}
    - python3 ./test.py --include ./${TEST_NAME}/
