language:
    - objective-c

install:
    - brew install cmake
    - brew install python3
    # install cmake
    - CMAKE_VERSION="3.0.0-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX="`pwd/_install`" -DCMAKE_BUILD_TYPE=Release -DCMAKE_USE_SYSTEM_CURL=YES
    -   cmake --build _builds --target install
    -   export PATH="`pwd`/_install/bin:${PATH}"
    - cd ..
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

script:
    - python3 ./jenkins.py
